=== Wyseyy/ProjectBank/WADCA1/public_html/WADCA1.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" 
elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productList">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" name="product">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="category" type="xs:string" />
                            <xs:element name="Name" type="xs:string" />
                            <xs:element name="Description" type="xs:string" />
                            <xs:element name="Quantity" type="xs:integer" />
                            <xs:element name="UnitPrice" type="xs:decimal" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="Code" type="xs:string" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Quantity">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:element name="UnitPrice">
        <xs:simpleType>
            <xs:restriction base="xs:decimal">
                <xs:minExclusive value="0"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>
    <xs:attribute name="code">
        <xs:simpleType>
            <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}-[0-9]{2}"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:attribute>
</xs:schema>

=== Wyseyy/ProjectBank/WADCA1/public_html/Product.xml
<?xml version="1.0" encoding="UTF-8"?>
<productList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
             xsi:noNamespaceSchemaLocation='WADCA1.xsd'>
    <product Code="101-01">
        <category>Mercedes</category>
        <Name>AMG</Name>
        <Description>biturbo v8</Description>
        <Quantity>15</Quantity>
        <UnitPrice>60.950</UnitPrice>
    </product>
    <product Code="101-02">
        <category>Ferrari</category>
        <Name>La Ferrari</Name>
        <Description>949bhp</Description>
        <Quantity>5</Quantity>
        <UnitPrice>420.000</UnitPrice>
    </product>
    <product Code="101-03">
        <category>McLaren</category>
        <Name>P1</Name>
        <Description>900nm</Description>
        <Quantity>10</Quantity>
        <UnitPrice>150.000</UnitPrice>
    </product>
    <product Code="101-04">
        <category>Ferrari</category>
        <Name>Spider</Name>
        <Description>Twin-Turbo V8</Description>
        <Quantity>22</Quantity>
        <UnitPrice>274.280</UnitPrice>
    </product>
    <product Code="101-05">
        <category>Land Rover</category>
        <Name>Defender</Name>
        <Description>V8 Engine</Description>
        <Quantity>18</Quantity>
        <UnitPrice>113.500</UnitPrice>
    </product>
    <product Code="101-06">
        <category>Ford</category>
        <Name>Focus</Name>
        <Description>345bhp</Description>
        <Quantity>30</Quantity>
        <UnitPrice>29990</UnitPrice>
    </product>
    <product Code="101-07">
        <category>Lamborghini</category>
        <Name>Gallardo</Name>
        <Description>V10 Engine</Description>
        <Quantity>2</Quantity>
        <UnitPrice>241.200</UnitPrice>
    </product>
    <product Code="101-08">
        <category>Dodge</category>
        <Name>Challenger</Name>
        <Description>717bhp</Description>
        <Quantity>15</Quantity>
        <UnitPrice>34.825</UnitPrice>
    </product>
    <product Code="101-09">
        <category>Bugatti</category>
        <Name>Chiron</Name>
        <Description>1000bhp</Description>
        <Quantity>1</Quantity>
        <UnitPrice>825.000</UnitPrice>
    </product>
    <product Code="101-10">
        <category>McLaren</category>
        <Name>Senna</Name>
        <Description>789bhp</Description>
        <Quantity>5</Quantity>
        <UnitPrice>850.000</UnitPrice>
    </product>
</productList>
